### ISSUE TITLE
Bug: Problem printing from iOS devices

### ISSUE THREAD

**Issue by Cengizhan-kcl** [gregnb/react-to-print#807]
On mobile devices, the content may not print or may appear as a blank page even if the trigger action is run.
Although the content can be printed, PDF margins appear on the page opened on iOS devices, preventing the content from fitting on the page.
While there is no problem with PDF margins on Windows, Mac PC and Android devices, this problem occurs on iOS.

```css
@media print {
  @page {
    margin: 0 !important;
    padding: 0 !important;
    size: auto !important;
    /* veya: size: A4 !important; */
  }
  html, body {
    visibility: hidden;
    overflow: visible;
    margin: 0 !important;
    padding: 0 !important;
    width: 100% !important;
  }
  body * {
    box-sizing: border-box !important;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  .print-content,
  .print-content * {
    visibility: visible !important;
  }
  .print-content {
    position: absolute !important;
    left: 0 !important;
    top: 0 !important;
    width: 100% !important;
    box-sizing: border-box !important;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
}
```

```jsx
const reactToPrintFn = useReactToPrint({
  contentRef: contentRef,
  preserveAfterPrint: true,
  copyShadowRoots: false,
  onAfterPrint: () => {
    setIsPrint(false);
  },
  pageStyle: "print",
  documentTitle:
    selectReport === undefined || selectReport.jumpStates.length === 0 || selectAthlete === undefined
      ? ""
      : ReportFuncs.getReportName({
        athlete: selectAthlete,
        reportTime: selectReport.testDate[0],
        reportType: selectTestType
      }),
});
```

````jsx
<DownloadButton
  selectReport={selectReport}
  setSelectTestType={setSelectTestType}
  getLanguageMap={getLanguageMap}
  startPrint={() => {
    if (selectReport !== undefined && selectReport.jumpStates.length !== 0) {
      setIsPrint(true);
      return new Promise((resolve) => {
        setTimeout(() => {
          setIsPrint(true);
          resolve();
          reactToPrintFn()
        }, 1000);
      });
    }
  }}
/>
```
